# general
[options]
Architecture           = auto
CheckSpace
DisableDownloadTimeout
HoldPkg                = pacman glibc
IgnorePkg              = linux-firmware linux-firmware-whence transmission-cli miniupnpc
LocalFileSigLevel      = Optional
ParallelDownloads      = 5
SigLevel               = Required DatabaseOptional
VerbosePkgLists

# artix             arch
# ------------------------------------
# system          | core
# world           | extra
# galaxy          | community
# lib32           | multilib
# universe        |
# gremlins        | testing
# galaxy-gremlins | community-testing
# lib32-gremlins  | multilib-testing
# goblins         | staging
# galaxy-goblins  | community-staging
# lib32-goblins   | multilib-staging

# artix
[system]
Include = /etc/pacman.d/mirrorlist
[world]
Include = /etc/pacman.d/mirrorlist
[galaxy]
Include = /etc/pacman.d/mirrorlist
# [lib32]
# Include = /etc/pacman.d/mirrorlist
# As of September 2023 the Universe repository has been discontinued. Virtually all of its packages have been moved to the Galaxy repository. Repository universe must be removed from /etc/pacman.conf to prevent errors.
# [universe]
# Server = https://universe.artixlinux.org/$arch
# [gremlins]
# Include = /etc/pacman.d/mirrorlist
# [galaxy-gremlins]
# Include = /etc/pacman.d/mirrorlist
# [lib32-gremlins]
# Include = /etc/pacman.d/mirrorlist
# [goblins]
# Include = /etc/pacman.d/mirrorlist
# [galaxy-goblins]
# Include = /etc/pacman.d/mirrorlist
# [lib32-goblins]
# Include = /etc/pacman.d/mirrorlist

# arch
# [core]
# Include = /etc/pacman.d/mirrorlist-arch
[extra]
Include = /etc/pacman.d/mirrorlist-arch
# Around two years ago, we've merged the [community] repository into [extra] as part of the git migration. In order to not break user setups, we kept these repositories around in an unused and empty state. We're going to clean up these old repositories on 2025-03-01.
# [community]
# Include = /etc/pacman.d/mirrorlist-arch
# [multilib]
# Include = /etc/pacman.d/mirrorlist-arch
# [testing]
# Include = /etc/pacman.d/mirrorlist-arch
# [community-testing]
# Include = /etc/pacman.d/mirrorlist-arch
# [multilib-testing]
# Include = /etc/pacman.d/mirrorlist-arch
# [staging]
# Include = /etc/pacman.d/mirrorlist-arch
# [community-staging]
# Include = /etc/pacman.d/mirrorlist-arch
# [multilib-staging]
# Include = /etc/pacman.d/mirrorlist-arch

# custom
[herecura]
Server = https://repo.herecura.eu/$repo/$arch
